In [130]:
 
from sqlalchemy import create_engine
def get_engine():
        return create_engine(
            f"postgresql+psycopg2://shikhabordia:readonly@localhost:5432/postgres",
            echo=False  # good for debugging
        )
import pandas as pd
sql_query = 'SELECT * FROM court'


df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   court_id  canton_id court_string
0         1          1        AG_GB
1         2          2       AI_BZG
2         3          2        AI_KG

In [126]:
tables = ['court', 'canton', 'chamber','court_name', 'canton_name',  'language', 'judgment', 'judgment_map', 'citation','citation_type','file','section', 'section_type',
 'num_tokens','decision','file_number','party', 'party_type', 'person', 'judicial_person_type', 'judicial_person',
 'spider','file', 'lower_court']

sql_query = 'SELECT * FROM court'

sql_query = 'SELECT * FROM chamber'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM lower_court'
#sql_query = 'SELECT * FROM citation_type'
#sql_query = 'SELECT * FROM judgment'

for table in tables:
    #print(table)
    sql_query = 'SELECT * FROM '+ table
    df_iterator = pd.read_sql(sql_query,get_engine().connect())
    print(table, len(df_iterator))

court 3
canton 2
chamber 3
court_name 15
canton_name 10
language 5
judgment 7
judgment_map 0
citation 0
citation_type 3
file 4382
section 0
section_type 6
num_tokens 0
decision 56
file_number 56
party 0
party_type 4
person 0
judicial_person_type 3
judicial_person 0
spider 2
file 4382
lower_court 0

In [132]:
tables = ['court', 'canton', 'chamber','court_name', 'canton_name',  'language', 'judgment', 'judgment_map', 'citation','citation_type','file','section', 'section_type',
 'num_tokens','decision','file_number','party', 'party_type', 'person', 'judicial_person_type', 'judicial_person',
 'spider','file', 'lower_court']

sql_query = 'SELECT * FROM court'

sql_query = 'SELECT * FROM chamber'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM lower_court'
#sql_query = 'SELECT * FROM citation_type'

#sql_query = 'SELECT * FROM judgment'

for table in tables:
    #print(table)
    sql_query = 'SELECT * FROM '+ table
    df_iterator = pd.read_sql(sql_query,get_engine().connect())
    print(table, len(df_iterator))

court 3
canton 2
chamber 3
court_name 15
canton_name 10
language 5
judgment 7
judgment_map 0
citation 0
citation_type 3
file 674
section 0
section_type 6
num_tokens 0
decision 9
file_number 9
party 0
party_type 4
person 0
judicial_person_type 3
judicial_person 0
spider 2
file 674
lower_court 0

In [198]:
tables = ['court', 'canton', 'chamber','court_name', 'canton_name',  'language', 'judgment', 'judgment_map', 'citation','citation_type','file','section', 'section_type',
 'num_tokens','decision','file_number','party', 'party_type', 'person', 'judicial_person_type', 'judicial_person',
 'spider','file', 'lower_court']

sql_query = 'SELECT * FROM court'

sql_query = 'SELECT * FROM chamber'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM lower_court'
#sql_query = 'SELECT * FROM citation_type'

#sql_query = 'SELECT * FROM judgment'

for table in tables:
    #print(table)
    sql_query = 'SELECT * FROM '+ table
    df_iterator = pd.read_sql(sql_query,get_engine().connect())
    print(table, len(df_iterator))

court 3
canton 2
chamber 3
court_name 15
canton_name 10
language 5
judgment 7
judgment_map 0
citation 0
citation_type 3
file 674
section 0
section_type 6
num_tokens 0
decision 9
file_number 9
party 0
party_type 4
person 0
judicial_person_type 3
judicial_person 0
spider 2
file 674
lower_court 0

In [154]:
sql_query = 'SELECT * FROM language'
df_iterator = pd.read_sql(sql_query,get_engine().connect())
df_iterator

sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect())
df_iterator#[df_iterator['html_raw'].isna()==True]


# sql_query = 'SELECT * FROM file where file_id =60'
# df_iterator = pd.read_sql(sql_query,get_engine().connect())
# df_iterator
text = df_iterator.loc[0,'pdf_raw']
text_1 = df_iterator['pdf_raw']
print(text_1)

0      anonymisierter Entscheid für Publikation - lös...
1      anonymisierter Entscheid für Publikation - lös...
2      anonymisierter Entscheid für Publikation - lös...
3      anonymisierter Entscheid für Publikation - lös...
4      anonymisierter Entscheid für Publikation - lös...
                             ...
669    Microsoft Word - VGE vom 11.12.2002.doc\n\n\n ...
670    Handelsgericht \n\n2. Kammer \n\n \n\n \n\nHSU...
671    AGVE-2006\n\n\n Weigert sich die Vormundschaft...
672    Entscheid des Verwaltungsgerichts vom 26. März...
673    Handelsgericht \n\n2. Kammer \n\n \n\n \n\nHOR...
Name: pdf_raw, Length: 674, dtype: object

In [163]:
sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect())
df_iterator#[df_iterator['html_raw'].isna()==True]


# sql_query = 'SELECT * FROM file where file_id =60'
# df_iterator = pd.read_sql(sql_query,get_engine().connect())
# df_iterator
text_2 = df_iterator.loc[0,'pdf_raw']
text_2 = df_iterator['pdf_raw']
print(text_2)

0      anonymisierter Entscheid für Publikation - lös...
1      anonymisierter Entscheid für Publikation - lös...
2      anonymisierter Entscheid für Publikation - lös...
3      anonymisierter Entscheid für Publikation - lös...
4      anonymisierter Entscheid für Publikation - lös...
                             ...
669    Microsoft Word - VGE vom 11.12.2002.doc\n\n\n ...
670    Handelsgericht \n\n2. Kammer \n\n \n\n \n\nHSU...
671    AGVE-2006\n\n\n Weigert sich die Vormundschaft...
672    Entscheid des Verwaltungsgerichts vom 26. März...
673    Handelsgericht \n\n2. Kammer \n\n \n\n \n\nHOR...
Name: pdf_raw, Length: 674, dtype: object

In [257]:
# for i in range(len(text_2)):
#     print(text_2[i]==text_1[i])

In [ ]:



from uuid import UUID

dec_ids =[UUID('1b78dd88-db6e-5f13-919c-5a7f520ed227'), UUID('e094e413-fc3d-5b27-a0b4-dba7817ae0e8'), UUID('eefb73b4-653d-5d04-9c0f-33735728a869'), UUID('f4721254-da4b-55e6-859a-07415e0bccfb'), UUID('0af55218-a657-5d2a-8343-51a43e891efa'), UUID('06d17bcf-ea14-5054-b75f-1c70dccd9089'), UUID('a592c302-e8d0-5200-9c2c-98285cc2018c'), UUID('ca6d8dcb-b1a0-5606-a20c-f54a876c3018'), UUID('460ac296-1533-539d-8755-6ab31b130655')]

In [7]:
sql_query = 'SELECT * FROM chamber'# WHERE court_id = 3'#AG_AK_001 '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   chamber_id  court_id  spider_id chamber_string
0           1         1          1     AI_BZG_001
1           2         2          1      AI_KG_001

In [8]:
sql_query = 'SELECT * FROM chamber'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   chamber_id  court_id  spider_id chamber_string
0           1         1          1     AI_BZG_001
1           2         2          1      AI_KG_001

In [17]:
sql_query = 'SELECT * FROM chamber WHERE chamber_id  like "CH_ED*" '#AG_AK_001 '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "CH_ED*" does not exist
LINE 1: SELECT * FROM chamber WHERE chamber_id  like "CH_ED*"
                                                     ^

[SQL: SELECT * FROM chamber WHERE chamber_id  like "CH_ED*" ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [4]:
sql_query = 'SELECT * FROM chamber WHERE chamber_id = "AG_AK_001" '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "AG_AK_001" does not exist
LINE 1: SELECT * FROM chamber WHERE chamber_id = "AG_AK_001"
                                                 ^

[SQL: SELECT * FROM chamber WHERE chamber_id = "AG_AK_001" ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [196]:
sql_query = 'SELECT * FROM section'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator)

0

In [197]:
df_iterator

Empty DataFrame
Columns: [section_id, decision_id, section_type_id, section_text]
Index: []

In [21]:
sql_query = 'SELECT * FROM judicial_person'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

Empty DataFrame
Columns: [decision_id, person_id, judicial_person_type_id, is_president]
Index: []

In [93]:
sql_query = 'SELECT * FROM decision'
df_iterator1 = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator1)
df_list[0]
len(df_iterator1), len(df_list[0])

df_iterator1

,decision_id,language_id,chamber_id,file_id,date,topic
0,03b1c203-0f26-5ea0-bad0-51dae9f743bc,1,380,7925,1996-07-22,
1,4ec76444-f120-5b97-93e6-0420cfcb0e4d,1,380,7926,2016-01-11,
2,295105e8-155d-56fe-804d-1c6e37a7ff99,1,380,7927,2015-12-04,
3,0f3521c0-5123-5be5-b68a-b250a55ec052,1,380,7928,2014-04-08,
4,a91f0eca-0bec-5be9-833f-e4aa49560170,1,380,7929,2016-12-05,
...,...,...,...,...,...,...
190852,cebf1aab-b51c-565c-915b-7cdca5e8700d,1,294,206385,2015-11-17,
190853,97ef6e1a-54e1-5179-bd34-e86816da8773,1,294,206386,2010-05-04,
190854,30b3d6d2-8250-5b3f-8055-2b3fe7eb4520,1,292,206387,2021-05-27,
190855,dc9d314a-6d06-5923-996b-19bfe043d311,1,292,206388,2019-12-17,
190856,c94f7ff9-1f1c-5b88-a957-f539161a4c0f,1,294,206389,2011-04-12,

In [94]:
sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

In [59]:
sql_query = 'SELECT * FROM decision'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

df_iterator

,decision_id,language_id,chamber_id,file_id,date,topic
0,03b1c203-0f26-5ea0-bad0-51dae9f743bc,1,380,7925,1996-07-22,
1,4ec76444-f120-5b97-93e6-0420cfcb0e4d,1,380,7926,2016-01-11,
2,295105e8-155d-56fe-804d-1c6e37a7ff99,1,380,7927,2015-12-04,
3,0f3521c0-5123-5be5-b68a-b250a55ec052,1,380,7928,2014-04-08,
4,a91f0eca-0bec-5be9-833f-e4aa49560170,1,380,7929,2016-12-05,
...,...,...,...,...,...,...
190852,cebf1aab-b51c-565c-915b-7cdca5e8700d,1,294,206385,2015-11-17,
190853,97ef6e1a-54e1-5179-bd34-e86816da8773,1,294,206386,2010-05-04,
190854,30b3d6d2-8250-5b3f-8055-2b3fe7eb4520,1,292,206387,2021-05-27,
190855,dc9d314a-6d06-5923-996b-19bfe043d311,1,292,206388,2019-12-17,
190856,c94f7ff9-1f1c-5b88-a957-f539161a4c0f,1,294,206389,2011-04-12,

In [3]:
import pandas as pd
sql_query = 'SELECT * FROM chamber'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

df_iterator

# chamber_df = df_iterator
# chamber_df[chamber_df['chamber_string']=="AG_OG_%"]
# chamber_df[chamber_df['chamber_string'].str.contains("AG_OG")]
#len(chamber_df),

NameError: name 'get_engine' is not defined

In [81]:
import os
folders = "data/spiders/"
chamber_set = set()
for folder in os.listdir(folders):
    #print(folders+folder)
   
    files = os.listdir(folders+folder)
    #print(len(files))
    files = ['_'.join([ x for x in f.split('_')[:3]]) for f in files]
    file_set = set(files)
    #print(len(file_set))
    chamber_set.update(file_set)

print(len(chamber_set))
chamber_set

20

{'AG_GB_001',
 'AG_HG_002',
 'AG_JG_001',
 'AG_OGA_001',
 'AG_OGA_002',
 'AG_OGA_003',
 'AG_OGA_004',
 'AG_OGA_005',
 'AG_OGA_006',
 'AG_OGA_999',
 'AG_OG_003',
 'AG_OG_004',
 'AG_OG_010',
 'AG_OG_012',
 'AG_OG_014',
 'AG_OG_999',
 'AG_VG_002',
 'AG_VSG_002',
 'AI_BZG_001',
 'AI_KG_001'}

In [80]:
files

['AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001']

In [92]:
list(chamber_set)[:5]

['BS_SVG_00', 'CH_VB_021', 'GE_CJ_013', 'TI_GIAR_0', 'VD_SR_001']

In [88]:
ch_set = set(list(chamber_df['chamber_string']))
len(ch_set)

424

In [91]:
print(len(ch_set - chamber_set), len(chamber_set-ch_set))
ch_set - chamber_set, chamber_set-ch_set

183 102

({'AG_AUK_001',
  'AG_JL_001',
  'AG_RR_001',
  'AG_SVWG_001',
  'AG_SVWG_002',
  'AG_SVWG_999',
  'AG_UPL_001',
  'AG_VB_003',
  'AG_VB_999',
  'AG_XX_001',
  'AI_BZG_001',
  'AI_UPL_001',
  'AR_KG_002',
  'AR_KG_003',
  'AR_OG_999',
  'AR_RR_001',
  'AR_SRK_001',
  'AR_UPL_001',
  'AR_VB_001',
  'AR_XX_001',
  'BE_NAB_001',
  'BE_NAB_002',
  'BE_NAB_003',
  'BE_NAB_999',
  'BE_SRK_001',
  'BE_UPL_001',
  'BE_VB_999',
  'BE_XX_001',
  'BL_UPL_001',
  'BL_XX_001',
  'BL_ZMG_001',
  'BS_APG_001',
  'BS_SVG_001',
  'BS_UPL_001',
  'BS_XX_001',
  'CH_BGE_001',
  'CH_BGE_002',
  'CH_BGE_003',
  'CH_BGE_004',
  'CH_BGE_005',
  'CH_BGE_006',
  'CH_BGE_007',
  'CH_BGE_008',
  'CH_BGE_009',
  'CH_BGE_010',
  'CH_BGE_011',
  'CH_BGE_999',
  'CH_BGer_001',
  'CH_BGer_002',
  'CH_BGer_004',
  'CH_BGer_005',
  'CH_BGer_006',
  'CH_BGer_008',
  'CH_BGer_009',
  'CH_BGer_010',
  'CH_BGer_012',
  'CH_BGer_013',
  'CH_BGer_014',
  'CH_BGer_015',
  'CH_BGer_016',
  'CH_BGer_999',
  'CH_BSTG_001',
  'CH_BVGE_001',
  'CH_EDÖB_001',
  'CH_EDÖB_002',
  'CH_EDÖB_003',
  'CH_EDÖB_004',
  'CH_EDÖB_999',
  'CH_PATG_001',
  'CH_UPL_001',
  'CH_WBK_001',
  'CH_XX_001',
  'FR_TAMA_001',
  'FR_UPL_001',
  'FR_XX_001',
  'GE_CAPJ_001',
  'GE_CJ_999',
  'GE_TAPI_001',
  'GE_UPL_001',
  'GE_XX_001',
  'GL_KG_999',
  'GL_UPL_001',
  'GL_XX_999',
  'GR_KG_012',
  'GR_UPL_001',
  'GR_VG_999',
  'GR_XX_001',
  'JU_TPI_006',
  'JU_TPI_007',
  'JU_TPI_999',
  'JU_UPL_001',
  'JU_XX_001',
  'LU_AUK_001',
  'LU_BKD_001',
  'LU_BZG_001',
  'LU_GSD_001',
  'LU_JSD_001',
  'LU_KG_005',
  'LU_RSH_001',
  'LU_UPL_001',
  'LU_XX_001',
  'NE_ARA_001',
  'NE_ASL_001',
  'NE_ASS_001',
  'NE_ATS_001',
  'NE_TR_999',
  'NE_UPL_001',
  'NE_XX_001',
  'NW_UPL_001',
  'NW_XX_001',
  'OW_UPL_001',
  'OW_XX_001',
  'SG_ABSK_001',
  'SG_KGN_001',
  'SG_KGN_999',
  'SG_UPL_001',
  'SG_VB_002',
  'SG_VB_999',
  'SG_VGN_001',
  'SG_VSG_001',
  'SG_VWEK_001',
  'SG_XX_001',
  'SH_UPL_001',
  'SH_XX_001',
  'SO_STG_001',
  'SO_UPL_001',
  'SO_VSG_001',
  'SO_XX_001',
  'SZ_UPL_001',
  'SZ_XX_001',
  'TG_UPL_001',
  'TG_XX_001',
  'TI_CARP_001',
  'TI_CATI_001',
  'TI_CRP_001',
  'TI_GIAR_001',
  'TI_GPC_001',
  'TI_TCAS_001',
  'TI_TCA_001',
  'TI_TPC_001',
  'TI_TRAC_001',
  'TI_TRAC_002',
  'TI_TRAC_003',
  'TI_TRAC_004',
  'TI_TRAC_005',
  'TI_TRAC_006',
  'TI_TRAC_007',
  'TI_TRAC_999',
  'TI_TRAP_001',
  'TI_TRAP_002',
  'TI_TRAP_999',
  'TI_TRPI_001',
  'TI_UPL_001',
  'TI_XX_999',
  'UR_UPL_001',
  'UR_XX_001',
  'VD_TPHA_001',
  'VD_UPL_001',
  'VD_XX_001',
  'VS_AG_001',
  'VS_BZG_001',
  'VS_BZG_002',
  'VS_BZG_003',
  'VS_BZG_004',
  'VS_BZG_005',
  'VS_BZG_006',
  'VS_BZG_007',
  'VS_BZG_008',
  'VS_BZG_009',
  'VS_BZG_999',
  'VS_SRK_001',
  'VS_UPL_001',
  'VS_XX_001',
  'ZG_UPL_001',
  'ZG_VG_999',
  'ZG_XX_001',
  'ZH_BRK_001',
  'ZH_KSG_001',
  'ZH_SOBE_001',
  'ZH_SRK_001',
  'ZH_SVG_001',
  'ZH_UPL_001',
  'ZH_XX_001'},
 {'AG_AUK_00',
  'AG_HG_001',
  'AG_HG_002',
  'AG_JG_001',
  'AG_LWRK_0',
  'AG_OGA_00',
  'AG_OGA_99',
  'AG_OG_003',
  'AG_OG_004',
  'AG_OG_010',
  'AG_OG_011',
  'AG_OG_012',
  'AG_OG_013',
  'AG_OG_014',
  'AG_OG_998',
  'AG_OSB_00',
  'AG_PRG_00',
  'AG_RGAR_0',
  'AG_SKBG_0',
  'AG_SRG_00',
  'AG_SVWG_0',
  'AG_UPL_00',
  'AG_VG_001',
  'AG_VG_002',
  'AG_VSG_00',
  'AI_BZG_00',
  'AR_UPL_00',
  'BE_NAB_00',
  'BE_SRK_00',
  'BE_UPL_00',
  'BL_ZMG_00',
  'BS_APG_00',
  'BS_SVG_00',
  'CH_BGE_00',
  'CH_BGer_0',
  'CH_BGer_9',
  'CH_BSTG_0',
  'CH_BVGE_0',
  'CH_EDÖB_0',
  'CH_EDÖB_9',
  'CH_PATG_0',
  'CH_UPL_00',
  'CH_WBK_00',
  'FR_UPL_00',
  'GE_CAPJ_0',
  'GE_TAPI_0',
  'JU_TPI_00',
  'LU_AUK_00',
  'LU_BKD_00',
  'LU_BZG_00',
  'LU_GSD_00',
  'LU_JSD_00',
  'LU_UPL_00',
  'NE_ARA_00',
  'NE_ASL_00',
  'NE_ASS_00',
  'NE_ATS_00',
  'OW_UPL_00',
  'SG_ABSK_0',
  'SG_KGN_00',
  'SG_KGN_99',
  'SG_OG_002',
  'SG_OG_003',
  'SG_OG_004',
  'SG_OG_005',
  'SG_OG_006',
  'SG_VGN_00',
  'SG_VSG_00',
  'SG_VWEK_0',
  'SH_UPL_00',
  'SO_STG_00',
  'SO_VSG_00',
  'TG_UPL_00',
  'TI_CARP_0',
  'TI_CATI_0',
  'TI_CRP_00',
  'TI_GIAR_0',
  'TI_TCAS_0',
  'TI_TCA_00',
  'TI_TPC_00',
  'TI_TRAC_0',
  'TI_TRAP_0',
  'TI_TRPI_0',
  'UR_AKBR_0',
  'UR_AKBR_9',
  'UR_REB_00',
  'VD_TPHA_0',
  'VD_UPL_00',
  'VS_AG_999',
  'VS_BZG_00',
  'VS_BZG_99',
  'VS_SRK_00',
  'VS_UPL_00',
  'XX_UPL_00',
  'ZG_UPL_00',
  'ZH_BRK_00',
  'ZH_KSG_00',
  'ZH_OG_006',
  'ZH_SOBE_0',
  'ZH_SRK_00',
  'ZH_SVG_00',
  'ZH_UPL_00'})

In [5]:
sql_query = 'SELECT * FROM court'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

df_iterator

# chamber_df = df_iterator
# chamber_df[chamber_df['chamber_string']=="AG_OG_%"]
# chamber_df[chamber_df['chamber_string'].str.contains("AG_OG")]
#len(chamber_df),

Empty DataFrame
Columns: [court_id, canton_id, court_string]
Index: []

In [30]:
sql_query = 'SELECT * FROM language'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])
df_iterator

   language_id iso_code
0            1       de
1            2       fr
2            3       it
3            4       en
4            5       nn

In [70]:
spider_dict_list = process_map(self.build_spider_dict, json_filenames, chunksize=self.chunksize)

NameError: name 'process_map' is not defined

In [ ]:
corresponding_pdf_path = Path(json_file).with_suffix('.pdf')
corresponding_html_path = Path(json_file).with_suffix('.html')

In [ ]:
court_dict_template = {key: '' for key in self.court_keys}

In [95]:
sql_query = 'SELECT * FROM decision'
sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])
len(df_iterator)

1254

In [ ]:
self.update(self.get_engine(self.db_scrc), df, 'decision',   ['language_id'], self.output_dir, None, 'decision_id')

In [94]:
sql_query = 'SELECT * FROM language'

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)

len(df_list[0])
df_list[0]

   language_id iso_code
0            1       de
1            2       fr
2            3       it
3            4       en
4            5       na

In [343]:
sql_query = 'SELECT * FROM chamber'
sql_query = 'SELECT * FROM canton'
sql_query = 'SELECT * FROM court'
sql_query = 'SELECT * FROM judgment_map'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM decision'
#sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)

df_list[0]

   judgment_id                           decision_id
0            2  1b78dd88-db6e-5f13-919c-5a7f520ed227
1            4  e094e413-fc3d-5b27-a0b4-dba7817ae0e8
2            2  f4721254-da4b-55e6-859a-07415e0bccfb
3            2  0af55218-a657-5d2a-8343-51a43e891efa

In [ ]:
sql_query = 'SELECT * FROM chamber'
sql_query = 'SELECT * FROM canton'
sql_query = 'SELECT * FROM court'
sql_query = 'SELECT * FROM judgment'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM decision'
#sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)

df_list[0]

   judgment_id                           decision_id
0            2  1b78dd88-db6e-5f13-919c-5a7f520ed227
1            4  e094e413-fc3d-5b27-a0b4-dba7817ae0e8
2            2  f4721254-da4b-55e6-859a-07415e0bccfb
3            2  0af55218-a657-5d2a-8343-51a43e891efa

In [345]:
sql_query = 'SELECT * FROM language'
sql_query = 'SELECT * FROM file'
sql_query = 'SELECT * FROM decision'
sql_query = 'SELECT * FROM citation'
#sql_query = 'SELECT * FROM decision'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

,citation_id,citation_type_id,decision_id,url,text
0,1,1,1b78dd88-db6e-5f13-919c-5a7f520ed227,None,BGE 130 III 230
1,2,1,1b78dd88-db6e-5f13-919c-5a7f520ed227,None,BGE 131 II 725
2,3,1,1b78dd88-db6e-5f13-919c-5a7f520ed227,None,BGE 127 II 725
3,4,1,eefb73b4-653d-5d04-9c0f-33735728a869,None,BGE 124 II 268
4,5,1,f4721254-da4b-55e6-859a-07415e0bccfb,None,BGE 131 II 724
5,6,1,0af55218-a657-5d2a-8343-51a43e891efa,None,BGE 130 III 225
6,7,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
7,8,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 78 II 27
8,9,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
9,10,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 289
10,11,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 289
11,12,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 103 II 176
12,13,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 103 II 183
13,14,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
14,15,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
15,16,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
16,17,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 81 III 62
17,18,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 119 II 17
18,19,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 106 II 194
19,20,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 106 II 189
20,21,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 81 III 63
21,22,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 103 Ia 457
22,23,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 106 Ia 28
23,24,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 111 Ia 214
24,25,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 118 Ia 410

In [115]:
sql_query = 'SELECT * FROM language'
sql_query = 'SELECT * FROM file'
#sql_query = 'SELECT * FROM decision'
#sql_query = 'SELECT * FROM citation'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
len(df_iterator)
df_iterator

,file_id,file_name,html_url,pdf_url,html_raw,pdf_raw
0,1,AG_OG_003_7c2e339cd83f1bbdccff_2017-04-03,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,"Entscheid des Obergerichts, 5. Zivilkammer, vo..."
1,2,AG_OGA_002_3d49d5dce342c99dfee6_2020-01-31,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
2,3,AG_OGA_002_-Handelsrecht-Bauhan_2020-06-20,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
3,4,AG_OGA_006_04b32d27a49d8880a3c3_2014-06-10,,https://www.ag.ch/media/kanton-aargau/jb/dokum...,,AGVE-2006\n\n\n§ 65a Abs. 4 EG ZGB \nDer Bunde...
4,5,AG_OG_012_-Handelsrecht-Bauhan_2020-01-31,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
...,...,...,...,...,...,...
1287,1286,AG_OG_012_-Handelsrecht-Zivilp_2019-06-06,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
1288,1287,AG_OGA_999_-Kindes--und-Erwachs_2014-04-03,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,AGVE-2006\n\n\nArt. 363 Abs. 2 Ziff. 3 ZGB \n...
1289,1288,AG_OGA_999_30fe0e8e7d5880fc42f6_2002-12-11,,https://www.ag.ch/media/kanton_aargau/dvi/doku...,,Microsoft Word - VGE vom 11.12.2002.doc\n\n\n ...
1290,1289,AG_HG_002_-Handelsrecht-Bauhan_2019-10-07,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Handelsgericht \n\n2. Kammer \n\n \n\n \n\nHSU...
1291,1290,AG_OG_004_56e0a91075a0155223b3_2013-10-18,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,AGVE-2006\n\n\n Weigert sich die Vormundschaft...

In [100]:
import pandas as pd

df = pd.DataFrame(columns=['Name', 'Age', 'City'])

print(df)

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [254]:
sql_query = 'SELECT * FROM language'
# sql_query = 'SELECT * FROM court'
sql_query = 'SELECT * FROM decision'
# sql_query = 'SELECT * FROM citation'
# sql_query = 'SELECT * FROM judicial_person_type'
# #sql_query = 'SELECT * FROM party_type'
# #sql_query = 'SELECT * FROM file_number'
# #sql_query = 'SELECT * FROM spider'
# sql_query = 'SELECT * FROM judgment'
# sql_query = 'SELECT * FROM person'

df_iterator = pd.read_sql(sql_query,get_engine().connect())
df_list = list(df_iterator)
df_list[0]
df_iterator['language_id'].drop_duplicates()

0    1
Name: language_id, dtype: int64

In [173]:
import pandas as pd
import dask.dataframe as dd

# Create a Pandas DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Convert to Dask DataFrame with 2 partitions
ddf = dd.from_pandas(df, npartitions=2)

# Perform an operation
result = ddf.groupby('A').sum()

# Compute the result
print(result.compute())

type(ddf)
ddf

   B
A
1  4
2  5
3  6

Dask DataFrame Structure:
                   A      B
npartitions=2
0              int64  int64
2                ...    ...
2                ...    ...
Dask Name: frompandas, 1 expression
Expr=df

In [181]:
ddf.partitions[0].compute()

   A  B
0  1  4
1  2  5

In [186]:
type(ddf.partitions[1].compute())
ddf.partitions[1].compute()

   A  B
2  3  6

In [ ]:
query = t.update().where(t.c.get(index_name or 'id') == bindparam('b_id')).values()

In [199]:
spider_list = [Path(spider).stem for spider in glob.glob( f"{str(self.spiders_dir)}/*")]

NameError: name 'glob' is not defined

In [201]:
decision_ids =[UUID('1b78dd88-db6e-5f13-919c-5a7f520ed227'), UUID('e094e413-fc3d-5b27-a0b4-dba7817ae0e8'), UUID('eefb73b4-653d-5d04-9c0f-33735728a869'), UUID('f4721254-da4b-55e6-859a-07415e0bccfb'), UUID('0af55218-a657-5d2a-8343-51a43e891efa'), UUID('06d17bcf-ea14-5054-b75f-1c70dccd9089'), UUID('a592c302-e8d0-5200-9c2c-98285cc2018c'), UUID('ca6d8dcb-b1a0-5606-a20c-f54a876c3018'), UUID('460ac296-1533-539d-8755-6ab31b130655')]
f" AND {where_decisionid_in_list(decision_ids)}" if self.decision_ids is not None and len(
            self.decision_ids) > 0 else ""

NameError: name 'UUID' is not defined

In [238]:
spiders =["AG_Weitere", "AI_Aktuell"]
from uuid import UUID
from scrc.utils.sql_select_utils import coverage_query, delete_stmt_decisions_with_df, get_total_decisions, join_decision_and_language_on_parameter,  where_decisionid_in_list, where_string_spider,join_decision_on_parameter
decision_ids =[UUID('1b78dd88-db6e-5f13-919c-5a7f520ed227'), UUID('e094e413-fc3d-5b27-a0b4-dba7817ae0e8'), UUID('eefb73b4-653d-5d04-9c0f-33735728a869'), UUID('f4721254-da4b-55e6-859a-07415e0bccfb'), UUID('0af55218-a657-5d2a-8343-51a43e891efa'), UUID('06d17bcf-ea14-5054-b75f-1c70dccd9089'), UUID('a592c302-e8d0-5200-9c2c-98285cc2018c'), UUID('ca6d8dcb-b1a0-5606-a20c-f54a876c3018'), UUID('460ac296-1533-539d-8755-6ab31b130655')]
only_given_decision_ids_string =f" AND {where_decisionid_in_list(decision_ids)}" if decision_ids is not None and len(
            decision_ids) > 0 else ""
spider = spiders[1]
query = f"file {join_decision_and_language_on_parameter('file_id', 'file.file_id')} " \
                               "LEFT JOIN chamber ON chamber.chamber_id = decision.chamber_id " \
                               "LEFT JOIN court ON court.court_id = chamber.court_id "

query= "SELECT * FROM " + query
print(query  )
df2 = pd.read_sql(query,get_engine().connect())

SELECT * FROM file  LEFT JOIN decision on decision.file_id=file.file_id  LEFT JOIN language ON language.language_id = decision.language_id  LEFT JOIN chamber ON chamber.chamber_id = decision.chamber_id LEFT JOIN court ON court.court_id = chamber.court_id

In [226]:
query = f"file {join_decision_and_language_on_parameter('file_id', 'file.file_id')} " \
                               "LEFT JOIN chamber ON chamber.chamber_id = decision.chamber_id " \
                               "LEFT JOIN court ON court.court_id = chamber.court_id "
type(query)

str

In [236]:
df1['spider_id'].drop_duplicates()

0    1.0
9    NaN
Name: spider_id, dtype: float64

In [235]:
df2['spider_id'].drop_duplicates()

0    1.0
9    NaN
Name: spider_id, dtype: float64

spider

In [ ]:
spider = spiders[0]
only_given_decision_ids_string = f" AND {where_decisionid_in_list(decision_ids)}" if decision_ids is not None else ""
        
tables = f"file {join_decision_on_parameter('file_id', 'file.file_id')} LEFT JOIN section ON section.decision_id = decision.decision_id"
where_string = f"file.file_id IN {where_string_spider('file_id', spider)} {only_given_decision_ids_string}"
print(where_string)
query= "SELECT * FROM " + tables + " WHERE " + where_string
print(query  )

df= pd.read_sql(query,get_engine().connect())
print(len(df))

file.file_id IN  (SELECT file_id from decision WHERE chamber_id IN (SELECT chamber_id FROM chamber WHERE spider_id IN (SELECT spider_id FROM spider WHERE spider.name = 'AG_Weitere')))   AND decision.decision_id IN ('1b78dd88-db6e-5f13-919c-5a7f520ed227','e094e413-fc3d-5b27-a0b4-dba7817ae0e8','eefb73b4-653d-5d04-9c0f-33735728a869','f4721254-da4b-55e6-859a-07415e0bccfb','0af55218-a657-5d2a-8343-51a43e891efa','06d17bcf-ea14-5054-b75f-1c70dccd9089','a592c302-e8d0-5200-9c2c-98285cc2018c','ca6d8dcb-b1a0-5606-a20c-f54a876c3018','460ac296-1533-539d-8755-6ab31b130655')
SELECT * FROM file  LEFT JOIN decision on decision.file_id=file.file_id  LEFT JOIN section ON section.decision_id = decision.decision_id WHERE file.file_id IN  (SELECT file_id from decision WHERE chamber_id IN (SELECT chamber_id FROM chamber WHERE spider_id IN (SELECT spider_id FROM spider WHERE spider.name = 'AG_Weitere')))   AND decision.decision_id IN ('1b78dd88-db6e-5f13-919c-5a7f520ed227','e094e413-fc3d-5b27-a0b4-dba7817ae0e8','eefb73b4-653d-5d04-9c0f-33735728a869','f4721254-da4b-55e6-859a-07415e0bccfb','0af55218-a657-5d2a-8343-51a43e891efa','06d17bcf-ea14-5054-b75f-1c70dccd9089','a592c302-e8d0-5200-9c2c-98285cc2018c','ca6d8dcb-b1a0-5606-a20c-f54a876c3018','460ac296-1533-539d-8755-6ab31b130655')

,file_id,file_name,html_url,pdf_url,html_raw,pdf_raw,decision_id,language_id,chamber_id,file_id,date,topic,section_id,decision_id,section_type_id,section_text
0,462,AG_GB_001_--10-GBAG--Zusammenr_2007-08-23,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,verwaltungsgerichtsurteil_§10_gbag_anonymisier...,f4721254-da4b-55e6-859a-07415e0bccfb,1,1,462,2007-08-23,,None,None,None,None
1,629,AG_GB_001_AGVE-2004-S--489-Nr-_2004-02-23,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,Microsoft Word - Entscheid vom 23.02.2004 Vere...,a592c302-e8d0-5200-9c2c-98285cc2018c,1,1,629,2004-02-23,,None,None,None,None
2,106,AG_GB_001_--10-GBAG--Zusammenr_2009-02-19,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,anonymisierter_beschwerdeentscheid_vger._1_10_...,1b78dd88-db6e-5f13-919c-5a7f520ed227,1,1,106,2009-02-19,,None,None,None,None
3,595,AG_GB_001_--8-und-22-GBAG--Ums_2009-04-22,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,anonymisierter_beschwerdeentscheid_2_22_gbag\n...,06d17bcf-ea14-5054-b75f-1c70dccd9089,1,1,595,2009-04-22,,None,None,None,None
4,648,AG_GB_001_AGVE-2001-S--563-Nr-_2001-12-05,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,Aus dem Protokoll des Regierungsrates des Kant...,460ac296-1533-539d-8755-6ab31b130655,1,1,648,2001-12-05,,None,None,None,None
5,126,AG_GB_001_--11-GBAG--Wert-der-_2015-10-29,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,Verwaltungsgericht \n2. Kammer \n\n \n \nWBE.2...,e094e413-fc3d-5b27-a0b4-dba7817ae0e8,1,1,126,2015-10-29,,None,None,None,None
6,635,AG_GB_001_AGVE-2002-S--643-Nr-_2002-09-12,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,anonymisierter Entscheid Betreibungsamt X Vers...,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,1,1,635,2002-09-12,,None,None,None,None
7,253,AG_GB_001_--10-GBAG--Zusammenr_2002-12-11,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,Microsoft Word - VGE vom 11.12.2002.doc\n\n\n ...,eefb73b4-653d-5d04-9c0f-33735728a869,1,1,253,2002-12-11,,None,None,None,None
8,511,AG_GB_001_--10-GBAG--Zusammenr_2009-10-21,,https://www.ag.ch/media/kanton-aargau/dvi/doku...,,Urteil\n\n\n Verwaltungsgericht \n2. Kammer \n...,0af55218-a657-5d2a-8343-51a43e891efa,1,1,511,2009-10-21,,None,None,None,None

In [323]:
sql_query = 'SELECT * FROM section_type'
#sql_query = 'SELECT * FROM num_tokens'
df= pd.read_sql(sql_query,get_engine().connect())
#df.columns#[df_iterator['html_raw'].isna()==True]


# # sql_query = 'SELECT * FROM file where file_id =60'
# # df_iterator = pd.read_sql(sql_query,get_engine().connect())
# # df_iterator
# text_2 = df_iterator.loc[0,'pdf_raw']
# text_2 = df_iterator['pdf_raw']
# print(text_2)
print(len(df))
df

7

   section_type_id            name
0                1       full_text
1                2          header
2                3           topic
3                4           facts
4                5  considerations
5                6         rulings
6                7          footer

In [334]:
df[df['section_type_id']==7]

,section_id,decision_id,section_type_id,section_text
6,16,1b78dd88-db6e-5f13-919c-5a7f520ed227,7,
13,23,e094e413-fc3d-5b27-a0b4-dba7817ae0e8,7,
20,30,eefb73b4-653d-5d04-9c0f-33735728a869,7,
27,37,f4721254-da4b-55e6-859a-07415e0bccfb,7,2. Kammer Der Präsident: Die Gerichtsschreiber...
34,44,0af55218-a657-5d2a-8343-51a43e891efa,7,Verwaltungsgericht des Kantons Aargau 2. Kamme...
41,51,06d17bcf-ea14-5054-b75f-1c70dccd9089,7,Rechtsmittelbelehrung\n1. Gegen diesen Entsche...
48,58,a592c302-e8d0-5200-9c2c-98285cc2018c,7,
55,65,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,7,
62,72,460ac296-1533-539d-8755-6ab31b130655,7,

In [340]:
sql_query = 'SELECT * FROM section'
#sql_query = 'SELECT * FROM num_tokens'
sql_query = 'SELECT * FROM citation'
#sql_query = 'SELECT * FROM citation_type'
df= pd.read_sql(sql_query,get_engine().connect())
#df.columns#[df_iterator['html_raw'].isna()==True]


# # sql_query = 'SELECT * FROM file where file_id =60'
# # df_iterator = pd.read_sql(sql_query,get_engine().connect())
# # df_iterator
# text_2 = df_iterator.loc[0,'pdf_raw']
# text_2 = df_iterator['pdf_raw']
# print(text_2)
print(len(df))
display(df)

25

,citation_id,citation_type_id,decision_id,url,text
0,1,1,1b78dd88-db6e-5f13-919c-5a7f520ed227,None,BGE 130 III 230
1,2,1,1b78dd88-db6e-5f13-919c-5a7f520ed227,None,BGE 131 II 725
2,3,1,1b78dd88-db6e-5f13-919c-5a7f520ed227,None,BGE 127 II 725
3,4,1,eefb73b4-653d-5d04-9c0f-33735728a869,None,BGE 124 II 268
4,5,1,f4721254-da4b-55e6-859a-07415e0bccfb,None,BGE 131 II 724
5,6,1,0af55218-a657-5d2a-8343-51a43e891efa,None,BGE 130 III 225
6,7,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
7,8,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 78 II 27
8,9,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
9,10,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 289
10,11,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 289
11,12,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 103 II 176
12,13,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 103 II 183
13,14,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
14,15,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
15,16,1,a592c302-e8d0-5200-9c2c-98285cc2018c,None,BGE 116 II 281
16,17,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 81 III 62
17,18,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 119 II 17
18,19,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 106 II 194
19,20,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 106 II 189
20,21,1,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,None,BGE 81 III 63
21,22,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 103 Ia 457
22,23,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 106 Ia 28
23,24,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 111 Ia 214
24,25,1,460ac296-1533-539d-8755-6ab31b130655,None,BGE 118 Ia 410

In [282]:
spider = spiders[1]
sql_query ="SELECT count(*) FROM decision LEFT JOIN language ON decision.language_id = language.language_id LEFT JOIN chamber ON chamber.chamber_id = decision.chamber_id LEFT JOIN spider ON spider.spider_id = chamber.spider_id WHERE spider.name = 'AI_Aktuell' AND language.language_id = 1"
df= pd.read_sql(sql_query,get_engine().connect())
df

   count
0      0

In [ ]:
spider = spiders[1]
sql_query ="SELECT count(*) FROM decision LEFT JOIN language ON decision.language_id = language.language_id LEFT JOIN chamber ON chamber.chamber_id = decision.chamber_id LEFT JOIN spider ON spider.spider_id = chamber.spider_id WHERE spider.name = 'AI_Aktuell' "
df= pd.read_sql(sql_query,get_engine().connect())
df

   count
0      0

In [ ]:
tokens_per_section = {  'section_id': str(34), 'num_tokens_spacy': row[k.name+'_spacy'],'num_tokens_bert': row[k.name+'_bert'] }

   count
0      0