In [6]:
synonyms ={'@Nr': '1', 'Definition': [{'@Id': '584', 'Typ': 'ab', 'Text': 'PSPV', 'Quelle': {'@Id': '1945865', '#text': '[{Amtliche Sammlung des Bundesrechts 2011 1031}http://www.admin.ch/ch/d/as/2011/1031.pdf]'}}, {'@Id': '71879', 'Typ': 'ap', 'Text': 'Verordnung vom 4. März 2011 über die Personensicherheitsprüfungen', 'Quelle': {'@Id': '3819835', '#text': '[{Amtliche Sammlung des Bundesrechts 2011 1031}http://www.admin.ch/ch/d/as/2011/1031.pdf]'}}, {'@Id': '1640600', 'Typ': 'nt', 'Text': 'SYS: SR 120.4'}]}

In [2]:
for definition in synonym['Definition']:
    print(definition)
    print("___")

{'@Id': '584', 'Typ': 'ab', 'Text': 'PSPV', 'Quelle': {'@Id': '1945865', '#text': '[{Amtliche Sammlung des Bundesrechts 2011 1031}http://www.admin.ch/ch/d/as/2011/1031.pdf]'}}
___
{'@Id': '71879', 'Typ': 'ap', 'Text': 'Verordnung vom 4. März 2011 über die Personensicherheitsprüfungen', 'Quelle': {'@Id': '3819835', '#text': '[{Amtliche Sammlung des Bundesrechts 2011 1031}http://www.admin.ch/ch/d/as/2011/1031.pdf]'}}
___
{'@Id': '1640600', 'Typ': 'nt', 'Text': 'SYS: SR 120.4'}
___

In [8]:
from collections import OrderedDict

for synonym in synonyms:
    print(synonym)
    for definition in synonym['Definition']:
        if isinstance(definition, OrderedDict):
            print({'type': definition['Typ'], 'text': definition['Text']})

@Nr

TypeError: string indices must be integers

In [1]:
 
from sqlalchemy import create_engine
def get_engine():
        return create_engine(
            f"postgresql+psycopg2://shikhabordia:readonly@localhost:5432/postgres",
            echo=False  # good for debugging
        )
import pandas as pd
sql_query = 'SELECT * FROM court'


df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

     court_id  canton_id court_string
0           1          2        AG_AK
1           2          2       AG_AUK
2           3          2        AG_JL
3           4          2        AG_OG
4           5          2       AG_OGA
..        ...        ...          ...
166       167         27       ZH_SRK
167       168         27       ZH_SVG
168       169         27       ZH_UPL
169       170         27        ZH_VG
170       171         27        ZH_XX

[171 rows x 3 columns]

In [15]:
sql_query = 'SELECT * FROM canton'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM lower_court'
#sql_query = 'SELECT * FROM citation_type'
#sql_query = 'SELECT * FROM judgment'

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

    canton_id short_code
0           1         CH
1           2         AG
2           3         AI
3           4         AR
4           5         BE
5           6         BL
6           7         BS
7           8         FR
8           9         GE
9          10         GL
10         11         GR
11         12         JU
12         13         LU
13         14         NE
14         15         NW
15         16         OW
16         17         SG
17         18         SH
18         19         SO
19         20         SZ
20         21         TI
21         22         TG
22         23         UR
23         24         VD
24         25         VS
25         26         ZG
26         27         ZH

In [16]:
sql_query = 'SELECT * FROM decision'

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

Empty DataFrame
Columns: [decision_id, language_id, chamber_id, file_id, date, topic]
Index: []

In [17]:
sql_query = 'SELECT * FROM chamber WHERE court_id = 3'#AG_AK_001 '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   chamber_id  court_id  spider_id chamber_string
0           3         3          2      AG_GB_001

In [18]:
sql_query = 'SELECT * FROM chamber'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

     chamber_id  court_id  spider_id chamber_string
0             1         1          1      AG_AK_001
1             2         2          1     AG_AUK_001
2             3         3          2      AG_GB_001
3             4         4          1      AG_JL_001
4             5         5          1      AG_OG_001
..          ...       ...        ...            ...
419         420       168         48     ZH_SRK_001
420         421       169         47     ZH_SVG_001
421         422       170         43     ZH_UPL_001
422         423       171         49      ZH_VG_001
423         424       172         43      ZH_XX_001

[424 rows x 4 columns]

In [19]:
sql_query = 'SELECT * FROM chamber WHERE chamber_id  like "CH_ED*" '#AG_AK_001 '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "CH_ED*" does not exist
LINE 1: SELECT * FROM chamber WHERE chamber_id  like "CH_ED*"
                                                     ^

[SQL: SELECT * FROM chamber WHERE chamber_id  like "CH_ED*" ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [4]:
sql_query = 'SELECT * FROM chamber WHERE chamber_id = "AG_AK_001" '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "AG_AK_001" does not exist
LINE 1: SELECT * FROM chamber WHERE chamber_id = "AG_AK_001"
                                                 ^

[SQL: SELECT * FROM chamber WHERE chamber_id = "AG_AK_001" ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [20]:
sql_query = 'SELECT * FROM court'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

     court_id  canton_id court_string
0           1          2        AG_AK
1           2          2       AG_AUK
2           3          2        AG_GB
3           4          2        AG_JL
4           5          2        AG_OG
..        ...        ...          ...
167       168         27       ZH_SRK
168       169         27       ZH_SVG
169       170         27       ZH_UPL
170       171         27        ZH_VG
171       172         27        ZH_XX

[172 rows x 3 columns]

In [12]:
sql_query = 'SELECT * FROM chamber'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

     chamber_id  court_id  spider_id chamber_string
0             1         1          1      AG_AK_001
1             2         2          1     AG_AUK_001
2             3         3          2      AG_GB_001
3             4         4          1      AG_JL_001
4             5         5          1      AG_OG_001
..          ...       ...        ...            ...
419         420       168         48     ZH_SRK_001
420         421       169         47     ZH_SVG_001
421         422       170         43     ZH_UPL_001
422         423       171         49      ZH_VG_001
423         424       172         43      ZH_XX_001

[424 rows x 4 columns]

In [21]:
sql_query = 'SELECT * FROM judicial_person'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

Empty DataFrame
Columns: [decision_id, person_id, judicial_person_type_id, is_president]
Index: []

In [92]:
sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

Exception during reset or similar
Traceback (most recent call last):
  File "/Users/shikhabordia/anaconda3/envs/scale/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "/Users/shikhabordia/anaconda3/envs/scale/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1432, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/shikhabordia/anaconda3/envs/scale/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 699, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

Exception during reset or similar
Traceback (most recent call last):
  File "/Users/shikhabordia/anaconda3/envs/scale/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy
    fairy._reset(
  File "/Users/shikhabordia/anaconda3/envs/scale/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1432, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/shikhabordia/anaconda3/envs/scale/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 699, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(5982, 7)

In [85]:
df_iterator['file_id']

0          1
1          2
2          3
3          4
4          5
        ...
5018    5019
5019    5020
5020    5021
5021    5022
5022    5023
Name: file_id, Length: 5023, dtype: int64

In [86]:
file_ids_list = ','.join(["'" + str(item) + "'" for item in file_ids])

,file_id,file_name,html_url,pdf_url,html_raw,pdf_raw
0,1,NE_TC_012_CDP-2015-143_2015-09-23,https://jurisprudence.ne.ch/scripts/omnisapi.d...,,"<!DOCTYPE html><html lang=""fr""><head><meta cha...",
1,2,NE_TC_010_CHAC-2000-139_2001-01-15,https://jurisprudence.ne.ch/scripts/omnisapi.d...,,"<!DOCTYPE html><html lang=""fr""><head><meta cha...",
2,3,NE_TC_012_CDP-2011-143_2011-04-08,https://jurisprudence.ne.ch/scripts/omnisapi.d...,,"<!DOCTYPE html><html lang=""fr""><head><meta cha...",
3,4,NE_TC_012_CDP-2019-326_2020-04-20,https://jurisprudence.ne.ch/scripts/omnisapi.d...,,"<!DOCTYPE html><html lang=""fr""><head><meta cha...",
4,5,NE_TC_009_CPEN-2022-39_2023-03-30,https://jurisprudence.ne.ch/scripts/omnisapi.d...,,"<!DOCTYPE html><html lang=""fr""><head><meta cha...",
...,...,...,...,...,...,...
5018,5019,ZH_VG_001_-VB-2019-00745_2020-01-16,https://vgrzh.djiktzh.ch/cgi-bin/nph-omniscgi....,,"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 T...",
5019,5020,ZH_VG_001_-VB-2018-00096_16-03-2018,https://vgrzh.djiktzh.ch/cgi-bin/nph-omniscgi....,,"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 T...",
5020,5021,ZH_VG_001_-VB-2019-00796_2020-09-01,https://vgrzh.djiktzh.ch/cgi-bin/nph-omniscgi....,,"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 T...",
5021,5022,ZH_VG_001_-VB-2024-00121_2024-08-21,https://vgrzh.djiktzh.ch/cgi-bin/nph-omniscgi....,,"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 T...",
5022,5023,ZH_VG_001_-VB-2010-00398_06-10-2010,https://vgrzh.djiktzh.ch/cgi-bin/nph-omniscgi....,,"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 T...",

In [70]:
spider_dict_list = process_map(self.build_spider_dict, json_filenames, chunksize=self.chunksize)

NameError: name 'process_map' is not defined

In [ ]:
corresponding_pdf_path = Path(json_file).with_suffix('.pdf')
corresponding_html_path = Path(json_file).with_suffix('.html')

In [ ]:
court_dict_template = {key: '' for key in self.court_keys}

In [ ]:
pdf_content_dict = self.extract_corresponding_pdf_content(corresponding_pdf_path)

In [ ]:
self.logger.debug(f"Extracting content from pdf file: \t {corresponding_pdf_path}")

In [42]:
sql_query = 'SELECT * FROM language'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   language_id iso_code
0            1       de
1            2       fr
2            3       it
3            4       en

In [71]:
sql_query = 'SELECT * FROM court_name'
sql_query = 'SELECT * FROM canton'
#sql_query = 'SELECT * FROM canton_name'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
sql_query = 'SELECT * FROM decision'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

Empty DataFrame
Columns: [decision_id, language_id, chamber_id, file_id, date, topic]
Index: []

In [94]:
with get_engine().connect() as connection:
    #df['file_id'] = pd.read_sql(query, engine.connect())["file_id"][0]
    df= pd.read_sql(sql_query,)
    connection.close()
df

TypeError: read_sql() missing 1 required positional argument: 'con'